# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartReplies-Demo' do
 pod 'Firebase/Core'
  pod 'Firebase/MLCommon'
  pod 'Firebase/MLNLSmartReply'

end
